# Generated by Django 5.1.7 on 2025-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0002_courierscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
