# Generated by Django 5.1.7 on 2025-03-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0003_user_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="Идентификатор чата группы", unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Название группы", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Описание группы (опционально)", null=True
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        blank=True,
                        help_text="Тип группы (например, 'курьеры', 'менеджеры' и т.д.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
