# Generated by Django 5.1.7 on 2025-04-21 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0004_telegramgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courierscore",
            name="points",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=6
            ),
        ),
    ]
