# Generated by Django 5.1.7 on 2025-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0002_orderhistory_processed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderentry",
            name="entry_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="master_product_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="master_product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="master_product_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="merchant_product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="merchant_product_sku",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="unit_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="unit_display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="unit_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderentry",
            name="weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name="orderentry",
            unique_together={("order", "entry_id")},
        ),
    ]
