# Generated by Django 5.1.7 on 2025-03-14 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0004_consumersentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumersentiment",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Оценка настроения потребителя (от 1 до 10)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
