# Generated by Django 5.1.7 on 2025-03-14 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0005_alter_consumersentiment_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Видео-доказательство доставки (опционально)",
                        null=True,
                        upload_to="delivery_proofs/",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время загрузки видео"
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Курьер, загрузивший видео",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Заявка, к которой приложено видео-доказательство",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_proof",
                        to="app_orders.order",
                    ),
                ),
            ],
        ),
    ]
