# Generated by Django 5.1.7 on 2025-03-14 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0006_deliveryproof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryproof",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Видео-доказательство доставки (опционально). Допустимые форматы: mp4, mov, avi, mkv.",
                null=True,
                upload_to="delivery_proofs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "mkv"]
                    )
                ],
            ),
        ),
    ]
