# Generated by Django 5.1.7 on 2025-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0008_alter_consumersentiment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumersentiment",
            name="sentiment",
            field=models.CharField(
                choices=[("excellent", "Отлично"), ("not_excellent", "Не отлично")],
                default="",
                help_text="Оценка настроения потребителя (Отлично или Не отлично)",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
