# Generated by Django 5.1.7 on 2025-04-21 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0010_alter_consumersentiment_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_code", models.CharField(max_length=50)),
                ("preparation_type", models.CharField(max_length=20)),
                ("telegram_chat_id", models.CharField(max_length=30)),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_preparition",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
