# Generated by Django 5.1.7 on 2025-04-21 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_orders", "0011_orderpreparation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderpreparation",
            constraint=models.UniqueConstraint(
                fields=("order_code", "preparation_type", "telegram_chat_id"),
                name="uniq_prep_event",
            ),
        ),
    ]
