# Generated by Django 5.1.7 on 2025-05-21 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cargo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoCostRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_per_mass_unit",
                    models.DecimalField(
                        decimal_places=2, help_text="Стоимость за 1 кг", max_digits=10
                    ),
                ),
                (
                    "cost_per_volume_unit",
                    models.DecimalField(
                        decimal_places=2, help_text="Стоимость за 1 м³", max_digits=10
                    ),
                ),
                (
                    "city",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_rate",
                        to="app_cargo.city",
                    ),
                ),
            ],
        ),
    ]
