# Generated by Django 5.1.7 on 2025-05-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cargo", "0003_alter_cargocostrate_cost_per_mass_unit_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="city_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_received",
                to="app_cargo.city",
            ),
        ),
    ]
