# Generated by Django 5.1.7 on 2025-05-26 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cargo", "0004_alter_cargo_city_to"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargocostrate",
            options={
                "verbose_name": "Ставка стоимости груза",
                "verbose_name_plural": "Ставки стоимости грузов",
            },
        ),
        migrations.AlterField(
            model_name="cargocostrate",
            name="city",
            field=models.OneToOneField(
                blank=True,
                help_text="Выбирите Город для которого нжно установить тариф",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_rate",
                to="app_cargo.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="cargocostrate",
            name="cost_per_mass_unit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите сколько баллов за 1 тонну в этом Городе",
                max_digits=10,
                verbose_name="Стоимость за 1 т",
            ),
        ),
        migrations.AlterField(
            model_name="cargocostrate",
            name="cost_per_volume_unit",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Укажите сколько баллов за 1 м³ в этом Городе",
                max_digits=10,
                verbose_name="Стоимость за 1 м³",
            ),
        ),
    ]
