# Generated by Django 5.1.7 on 2025-05-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_cargo",
            "0005_alter_cargocostrate_options_alter_cargocostrate_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={"verbose_name": "Груз", "verbose_name_plural": "Грузы"},
        ),
        migrations.AlterField(
            model_name="cargo",
            name="city_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Город отправления, может быть пустым если от постовщика",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_sent",
                to="app_cargo.city",
                verbose_name="Город отправки",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="city_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Город, который ожидает прием товара, так же может быть пустым, если отгржаем оптовику",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargoes_received",
                to="app_cargo.city",
                verbose_name="Город приема",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и Время создания записи о грузе",
                verbose_name="Дата/Время",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="id_external",
            field=models.BigIntegerField(
                help_text="ID из другой системы с уникальным значеним",
                unique=True,
                verbose_name="Внешний ИД",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="mass",
            field=models.FloatField(
                blank=True,
                help_text="Показывает какая масса этого грузза",
                null=True,
                verbose_name="Масса",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="volume",
            field=models.FloatField(
                blank=True,
                help_text="Показывает какой объём этого груза",
                null=True,
                verbose_name="Объём",
            ),
        ),
    ]
