# Generated by Django 5.1.7 on 2025-05-26 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cargo", "0006_alter_cargo_options_alter_cargo_city_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workdistribution",
            options={
                "verbose_name": "Распределение работы и баллов сотрудника",
                "verbose_name_plural": "Распределение работ и баллы сотрудников",
            },
        ),
        migrations.AlterModelOptions(
            name="workunit",
            options={
                "verbose_name": "Работа с грузом",
                "verbose_name_plural": "Работы с грузами",
            },
        ),
        migrations.AlterField(
            model_name="workdistribution",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Струдик",
            ),
        ),
        migrations.AlterField(
            model_name="workdistribution",
            name="scanned_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и Время создания записи",
                verbose_name="Дата/Время",
            ),
        ),
        migrations.AlterField(
            model_name="workdistribution",
            name="score_share",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Баллы, которые получил сотрудник выполняя работу с грузом",
                max_digits=10,
                verbose_name="Баллы",
            ),
        ),
        migrations.AlterField(
            model_name="workdistribution",
            name="work_unit",
            field=models.ForeignKey(
                help_text="Указывает на конкретную работу с/над грузом",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="app_cargo.workunit",
                verbose_name="Работа с грузом",
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="cargo",
            field=models.ForeignKey(
                help_text="Груз с которым производятся раюоты",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_units",
                to="app_cargo.cargo",
                verbose_name="Груз",
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="city",
            field=models.ForeignKey(
                help_text="Город в котором производятся работы",
                on_delete=django.db.models.deletion.PROTECT,
                to="app_cargo.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и Время создания записи",
                verbose_name="Дата/Время",
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="mass_units",
            field=models.FloatField(default=0, verbose_name="Масса"),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="total_score",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Суммарное количество баллов за работу по этому Грузу в этом Городе",
                max_digits=10,
                verbose_name="Сумма баллов",
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="volume_units",
            field=models.FloatField(default=0, verbose_name="Объём"),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="work_type",
            field=models.CharField(
                choices=[("load", "Погрузка"), ("unload", "Разгрузка")],
                help_text="Тип производимой работы",
                max_length=10,
                verbose_name="Тип работы",
            ),
        ),
    ]
